cmdargs:
  severity: style_problem

policies:

  ProhibitAbbreviationOption:
    enabled: false

  ProhibitCommandRelyOnUser:
    enabled: true

  ProhibitImplicitScopeBuitlinVariable:
    enabled: false

  ProhibitImplicitScopeVariable:
    enabled: false
